### ISSUE TITLE
Resist Fingerprinting problem

### ISSUE THREAD

**Issue by maverick74** [aqt/webext-popup#39] opened 2019-04-11 09:03 UTC
If, in **about:config**, the key **privacy.resistFingerprinting** is set to **True**, the addon cannot set the popup window size/position correctly.

Considering this will be coming soon to Firefox, it may represent a bigger problem

**Comment by aqt** [comment] 2019-04-11 15:46
Interesting, haven't heard of this feature before.
I have a working fix that updates the size after creating the window, that introduces a flicker but it's better than nothing.

I might add a toggle to activate the workaround before pushing an update, since circumventing the feature would harm privacy it should be an active choice.

**Comment by maverick74** [comment] 2019-04-11 16:53
What about manual setting the screen resolution on the addon? 

Would that work?

**Comment by aqt** [comment] 2019-04-11 20:14
Sorry, I don't understand what that would solve, could you explain it another way?

**Comment by maverick74** [comment] 2019-04-15 09:50
Well, i'm not sure if it would work and, even if it did, it would be just another way of getting the same result you already have. This would also only work if a few assumptions was made (such as the screen resolution be kept the same). 

But, let's see if i can explain it (please understand that i have no knowledge whatsoever of addon development):

You say you have a way to update (or get) the window size, so that the addon can be placed in a predetermined position with a specific size... so, the addon's api can get the screen resolution.
Can't that screen resolution value be permanently stored and reused later?

(but if it can't be obtained automatically, one could also manually specify it on some field form)

**Comment by maverick74** [comment] 2019-04-15 10:26
I've reported the same bug on PopupVideo (https://github.com/ettoolong/PopupVideo/), Issue 15 ("Window Size and privacy.resistFingerprinting").

Ettoolong came up with an idea close to what i suggested - and probably something that actually works, unlike mine ahahaha. 
He probably explained it a lot better than me ;)

**Comment by aqt** [comment] 2019-04-15 14:18
I think I understand the confusion. The addon doesn't need to know the screen resolution when creating a window, nor does it use it when creating windows. I don't know if PopupVideo uses it for example to create "maximized" popup window, but this addon doesn't use the screen resolution at all.

The problem was that when creating a window Firefox would ignore the position/size set by the addon, and instead use pre-defined "safe" values. In my case this would be a size of 1000x1000.

Since Firefox only overrides these options when _creating_ a window, updating the window _afterwards_ with the correct size solves the problem, no further action is necessary. This might however be unintended behaviour and be corrected in later versions of Firefox, and at that point I don't think there's anything I can do to work around it except maybe toggling the setting off/on which I don't think is an acceptable solution.

**Comment by maverick74** [comment] 2019-04-15 14:55
I see... sorry for my mistake then :)

Yes, toggling the setting off/on **one time** is one thing and i would consider accepting it, doing it every time we use the addon is another that i would not be ok with. 
That is not a solution. 

I agree with you :)

**Comment by aqt** [comment] 2019-05-11 21:33
This will be included in the next release, I also added a new section for enabling workarounds such as these. It will be activated when updating the extension but disabled for new installs.

I want to take a look at some other issues first but will make the release tomorrow.

**Closed by aqt** 2019-05-11 21:33 UTC
Labels: bug
