### ISSUE TITLE
1 pixel line at the top of the content area

### ISSUE THREAD

**Issue by mirh** [aqt/webext-popup#49] opened 2022-01-15 20:31 UTC
1. open some [black image](https://upload.wikimedia.org/wikipedia/commons/2/21/Solid_black.svg). 
2. use some window -> fullscreen tool (such as [magpie](https://github.com/Z-Dante/Magpie))
3. notice that the topmost line of pixels is white

I think that's the UI divider that should usually "beautify" the transition between working area and buttons/tabs bars. 
https://old.reddit.com/r/FirefoxCSS/comments/ane60t/how_to_remove_the_border_of_the_tabstoolbar_in_my/

**Comment by aqt** [comment] 2022-01-15 21:19
Hi, it's correct that it's that divider. The color can be modified but it is not possible to change it only for popup windows so I cannot solve this in the extension.

I made a new CSS rule for userChrome.css since that reddit post seems outdated (`#navigator-toolbox` has border-bottom now, not `#TabsToolbar`), and I also made it only apply when the toolbar is hidden:
```
:root[chromehidden~="toolbar"] #navigator-toolbox-background {
  display: none;
}
```

I'll take a look at how to contribute code to Firefox and see if I can get this fix into it.

**Comment by aqt** [comment] 2022-01-15 21:56
> The clone can take from 40 minutes to two hours (depending on your connection) and the repository should be less than 5GB (~ 20GB after the build).

On second thought I'll settle for only reporting the bug and fix in their bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1750391

**Comment by mirh** [comment] 2022-01-16 00:50
Thank you for your outrageously quick reply. 
(you seem to have quoted some random piece of text)

**Comment by aqt** [comment] 2022-01-17 19:15
It was just a quick quote from their [quick reference](https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html#firefox-contributors-quick-reference) on how to contribute, to explain the reason why I ended up not contributing a patch to their source code for this bug.

I'll close this issue for now since the issue is in Firefox. Thanks!

**Closed by aqt** 2022-01-17 19:15 UTC

**Comment by mirh** [comment] 2022-01-17 23:22
Thanks for your good nature
