### ISSUE TITLE
Popup on URL Detection

### ISSUE THREAD

**Issue by maverick74** [aqt/webext-popup#12] opened 2018-04-18 15:13 UTC
URL Detection: as soon as we load a specific URL would be nice it would automatically popup the page.

This is extremely useful in a business environment where companies constantly work with webservices.

It would also allow those same users to set desktop icons to those URL/Services that would quickly launch them in a popup

**Comment by aqt** [comment] 2018-04-18 17:01
Preferably I'd like to keep the extension somewhat simple without too many different rules and options, unless the user experience would be greatly improved.

**Comment by maverick74** [comment] 2018-04-18 18:15
Yes, i understand you. But still that will require that you open the browser, go to the desired page, and once there one still need to press the popup button, while this was it would be more "direct".

Anyway, naturally, it's your call! I just submitted the bug because this is what we're searching for. :)

Thank you for your time and reply :)

**Comment by aqt** [comment] 2018-04-18 20:32
Thank you, I'm happy to receive any and all suggestions!

**Comment by aqt** [comment] 2018-09-12 19:59
After reconsideration (but mostly due to more feedback) I've decided to add this feature after all. In the case of more options cluttering the UI I could in most cases hide them in an "advanced" menu.

**Comment by maverick74** [comment] 2018-09-17 09:33
nice to know about that :) will keep an eye on this. Any eta?

**Comment by aqt** [comment] 2018-09-17 15:03
I had at look at it this weekend but ran into some problems. They're not hard to fix, just need to explore the api a bit more to decide how to solve them.

I can't really give an honest eta since it depends on how much time I can free up. Hopefully it's done this week, but it may take longer.

**Comment by aqt** [comment] 2018-09-20 16:58
I've published a new version (1.3.6) where this feature is included

**Comment by grahamperrin** [comment] 2018-09-20 19:13
Thanks! 

Tested with Waterfox 56.2.3 and Firefox 62.0_2,1 on FreeBSD-CURRENT. 

The feature seems to be not effective with Waterfox, does it use an API that's in a particular version of Firefox?

**Comment by aqt** [comment] 2018-09-20 19:51
Should be working from Firefox 45 and up according to the documentation, haven't tried that far back though. I'm using Firefox 62.0 and developer edition 63.0b7 on x64 Windows 10.

Do you see any error messages if you debug the addon?
Go to about:debugging, press debug on PopUp. Note that messages from other addons are included, I don't think there's a way to filter those out so keep that in mind)

I'll get a VM with FreeBSD (12.0-CURRENT?) up and running tomorrow or the weekend and see if I can find anything.

**Comment by grahamperrin** [comment] 2018-09-20 20:11
Thanks. Probably not specific to FreeBSD, but I thought I should mention the OS. 

Debugging now …

**Comment by grahamperrin** [comment] 2018-09-20 20:17
With automation enabled for `mozilla.org`, at https://www.waterfoxproject.org/en-US/ I click the _POWERED BY mozilla_ icon and get these lines in the Console: 

----

…
- Error: WebExtension context not found! Extension `Parent.jsm:778:13`
- uncaught exception: undefined `(unknown)`
- Services.locale.getApplicationLocale is not a function  `grid.jsm:763`
- TypeError: regex_list is undefined[Learn More]  `content_script.js:7:21`
- Error: Could not establish connection. Receiving end does not exist. `undefined`
- Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. ExtensionCommon.jsm:304

…

(Disclosing the details for _Services.locale.getApplicationLocale is not a function_ shows lines for findbartweak, nothing more.)

**Comment by aqt** [comment] 2018-09-20 20:35
Doesn't look relevant to me unfortunately, unless you only get these lines in this case? I think the _.jsm_ files were used in the old extension system, and _content_script.js_ is also from another extension.
You might want to try using a clean profile in case another extension is interfering, but I don't think it is very likely. 

If you don't see an error from a file named _background.js_ it will likely require deeper troubleshooting to find the cause.

**Comment by maverick74** [comment] 2018-09-21 09:55
Hi. It's great news.

However it does not work if:
on windows you create a desktop shortcut to a webpage.

it opens but the the webpage does not popout

**Comment by aqt** [comment] 2018-09-21 15:50
I'll see if I can see an issue with that as well.

**Comment by maverick74** [comment] 2018-09-26 09:50
@aqt I'm using x64 - FF62.0.2 on a Windows 10 machine (with 18.03).

I just dragged the page to the desktop to create the shortcut (either from the URL bar or from the bookmarks toolbar). One important detail is that firefox cannot have restore session enabled! It has to startup without any other webpages - except for the one from the shortcut.

I guess this might be a security measure from Firefox somehow...

**Comment by maverick74** [comment] 2018-11-14 15:20
Update: Addon working perfectly here!!!

Thank You :D

**Comment by aqt** [comment] 2018-11-14 20:38
Great news, I think I can close this issue then.

**Closed by aqt** 2018-11-14 20:38 UTC
Labels: enhancement
